### ISSUE TITLE
Packages cannot be authenticated!

### ISSUE THREAD

**Issue by rlanore** [ltb-project/openldap-deb#11]
In stretch apt can't verify packages

```
wget -O - https://ltb-project.org/lib/RPM-GPG-KEY-LTB-project | sudo apt-key add -
OK
```

```
cat /etc/apt/sources.list.d/ltb-project.list 
deb      [arch=amd64] "https://ltb-project.org/debian/stretch" stretch main
```

```
apt-get -q -y install openldap-ltb=2.4.45.1
WARNING: The following packages cannot be authenticated!
  berkeleydb-ltb openldap-ltb
E: There were unauthenticated packages and -y was used without --allow-unauthenticated

```

**Comment by coudot** [comment]
Strange, because they seem well signed in the repo:

$ dpkg-sig -c openldap-ltb_2.4.45.1_amd64.deb
Processing openldap-ltb_2.4.45.1_amd64.deb...
GOODSIG _gpgbuilder 3FC3FD92ABA3975D2BEB95A70AC51F926D45BFC5 1504615356

$ dpkg-sig -c berkeleydb-ltb_4.6.21.NC-4-patch4_amd64.deb 
Processing berkeleydb-ltb_4.6.21.NC-4-patch4_amd64.deb...
GOODSIG _gpgbuilder 3FC3FD92ABA3975D2BEB95A70AC51F926D45BFC5 1504616890

**Comment by davidcoutadeur** [comment]
Tested today on my Debian buster/sid, with stretch LTB repository.
Same command used:
apt-get -q -y install openldap-ltb=2.4.45.1
Everything seems ok. Don't know what could be wrong with your system. Please let us know if you investigate.

**Comment by nqb** [comment]
Hello,

On Debian Stretch up-to-date (9.3), I can't reproduce.
