### ISSUE TITLE
Mark conflict with slapd?

### ISSUE THREAD

**Issue by rongten** [ltb-project/openldap-deb#46]
Hello, 

 at least on Ubuntu 18.04, shouldn't the package slapd be in conflict with these packages? 

 Installing both at the same time seems to bring some issues due to PATH and overwritten systemd files.

**Comment by davidcoutadeur** [comment]
Hello,

openldap-ltb is a replacement to default debian openldap packaging.
Every openldap-ltb file lie in a separate directory, except for systemd file.

I think historically the reason was to have exactly the same name showing this is exactly the same service.
For having both services working, you can rename one of the systemd file.
Maybe we can also think to a different name for systemd script for the future, for having a null intersection of package files. @coudot what's your opinion on this?

**Comment by coudot** [comment]
I think we have the same issue in RPM, the conflict will be with the service name. We could maybe use slapd-ltb name when providing 2.5 and explain how to rename it to slapd. But this would bother many users, to be discussed.

**Comment by davidcoutadeur** [comment]
2.5 being released quite soon, it solves this issue.
