### ISSUE TITLE
Release 2.4.52 packages

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-deb#48]

**Comment by davidcoutadeur** [comment]
As I suspected, there are build problems on old platforms because of the new requirement of a recent openssl version

Error message at build:
```
undefined reference to `SSL_CTX_set1_curves_list'
```

Errors are happening on these OS:
- debian 7-32: `OpenSSL 1.0.1t  3 May 2016`
- debian 7-64: `OpenSSL 1.0.1t  3 May 2016`
- debian 8-64: `OpenSSL 1.0.1t  3 May 2016`

Debian 9 and 10 are working, because they have openssl versions `1.1.0l` and `OpenSSL 1.1.1d` respectively.

**Comment by davidcoutadeur** [comment]
As I suspected, there are build problems on old platforms because of the new requirement of a recent openssl version

Error message at build:
```
undefined reference to `SSL_CTX_set1_curves_list'
```

Errors are happening on these OS:
- debian 7-32: `OpenSSL 1.0.1t  3 May 2016`
- debian 7-64: `OpenSSL 1.0.1t  3 May 2016`
- debian 8-64: `OpenSSL 1.0.1t  3 May 2016`

Debian 9 and 10 are working, because they have openssl versions `1.1.0l` and `OpenSSL 1.1.1d` respectively.

**Comment by coudot** [comment]
So it may be time to remove support for these old distributions

We will keep the latest working OpenLDAP version in repositories (2.4.51) and advertise in release notes

**Comment by davidcoutadeur** [comment]
I have made some researches if there were external repositories maintaining openssl for old debian versions, but I have found nothing. It would be possible to add temporarily repositories of Debian 9 or Debian 10 to install new openssl versions, but this would mean selecting a way other users maybe haven't followed, leading to compilation / execution errors.

So I agree, the best option is here to drop support for new openldap versions...

**Comment by coudot** [comment]
Yes, we do what we can, and will encourage users to migrate on recent distributions.
