### ISSUE TITLE
No log file after install until rsyslog is restarted

### ISSUE THREAD

**Issue by soisik** [ltb-project/openldap-deb#86]
Hi,

After installing and configuring openldap-ltb 2.5.9.1 on ubuntu 20.04, the log file openldap.log was not created in /var/log/. Configuration seemed fine in rsyslog.conf. After restarting rsyslog using `systemctl restart rsyslog`, the log file did appear as expected.

**Comment by davidcoutadeur** [comment]
Hello,

That's because *syslog is not reloaded/restarted.

However, the logrotate is doing the job, so at a moment, the log will start working.

Anyway, a fix is interesting to immediately restart *syslog.

TODO:
- find out a way to get the corresponding *syslog implementation
- restart it in postinst / postrm
- commit the fix only in OpenLDAP 2.5 branch (no syslog in 2.6)

Thanks for the report.

**Comment by davidcoutadeur** [comment]
Done in 79ee938

As it can be any implementation of syslog (syslog, rsyslog, syslog-ng,...), I have made a simple fix:
Check if rsyslog is present and started -> if so, restart it after adding openldap rsyslog configuration
